### ISSUE TITLE
error with SHT75

### ISSUE THREAD

**Issue by mamdouh1** [mk-fg/sht-sensor#5]
I am trying to read temperature and humidity from SHT75 sensor and I have installed sht-sensor library 
I connected the sensor as below 
VDD-> 3.3
GND-> PI GND 
SCK-> GPIO 21
DATA-> GPIO 17

my raspberry run with raspbian and I wrote the following code 

from sht_sensor import Sht
sht = Sht(21, 17)
print 'Temperature', sht.read_t()
print 'Relative Humidity', sht.read_rh()

I got the following error 

Temperature
Traceback (most recent call last):
  File "sht_sens.py", line 3, in <module>
    print 'Temperature', sht.read_t()
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 257, in read_t
    t_raw = self._get_meas_result(self.cmd.t)
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 197, in _get_meas_result
    self._send(cmd)
  File "/usr/local/lib/python2.7/dist-packages/sht_sensor/sensor.py", line 157, in _send
    raise ShtCommFailure('Command ACK failed on step-1')
sht_sensor.sensor.ShtCommFailure: Command ACK failed on step-1

so kindly advice what I have to do to solve this problem

**Comment by mk-fg** [comment]
I'd suggest checking whether sensor is connected to specified pins and/or working at all.

Basically, command gets sent on a wire and at the very first step where there should be response (acknowledgement) from the sensor, there is none.
This would happen if specified pins would be not connected to anything for example, but might also be some issue with the sensor if everything is connected correctly and it just doesn't respond, which is usually less likely.

I'd suggest paying close attention to pin numbers btw, as 21 and 17 in your example seem like an odd choice, given that they're located at the opposite sides of the header, maybe you want 17 and 27, which are next to each other?
Or guess maybe you've picked these numbers from the readme, where I think I've tested the thing on Beagleboard, which has these ones close-by, unlike RPi.

Note that there should be a pull-up resistor connected with this sensor on the data pin, and this module doesn't tinker with internal RPi resistors (which can only be enabled via RPi-specific registers).

I think Pi-Sht1x module (see Links section in the readme), which uses RPi.GPIO (and /dev/mem interface) might actually set internal pull-up resistor, so if that is desirable, might want to use that one instead.

I'll close the issue as I don't think there's any indication of anything going wrong in the code, but feel free to ask/post stuff here anyway, might be able to answer.

**Comment by mk-fg** [comment]
Also note that Raspberry Pi 1 doesn't even have GPIO 21, but I guess you mean RPi2 or RPi3 (newer boards) above.
