### ISSUE TITLE
Python 3 Incompatibility

### ISSUE THREAD

**Issue by kizniche** [mk-fg/sht-sensor#8]
What are the chances we can get this module Python 3 compatible? I had a user [submit an issue](https://github.com/kizniche/Mycodo/issues/437) after I updated the software I develop to Python 3, but I hadn't tested my SHT 75 for compatibility. I'm not sure how difficult it will be, but I'm going to attempt it this weekend.

**Comment by kizniche** [comment]
Reference [here](https://github.com/kizniche/Mycodo/issues/436), too.

**Comment by mk-fg** [comment]
Hey,

Chance of py3 update is pretty low, unfortunately, as I don't have the sensor to test it with properly, nor really the motivation, at least until I'll ever need/use it myself again.
Guess maybe I should add a note to that effect to the README too.


Code should be pretty simple and low-maintenance, so if you have something to test it with, should probably take only a few hours to rewrite at most (throwing away parts that are in py3 already, like enums and `time.monotonic()`), and then maybe just keep it in-tree or something.

Note that another option might be to use e.g. https://github.com/drohm/pi-sht1x/ that already is for python 3.x, but maybe replacing gpio bits to something non-RPi-specific.

And if you'll be updating this code, I'd suggest to replace gpio here too, as sysfs kernel API for it is deprecated, and new-ish (few years old by now) ioctl-based one should be easy to use via fcntl.ioctl and such, likely simplier than sysfs paths.


Either way, best of luck and sorry for making migration/maintenance a bit more troublesome.

**Comment by mk-fg** [comment]
You seem to have obsoleted my comment right as I was composing it :)

Will merge the update. Can't really test if it works, but guess it does.

**Comment by kizniche** [comment]
Okay. Thanks. I was writing a reply, then saw your next comment come in. I noticed your first was very timely, right as I made the pull request. I think I may know someone with other SHT sensors, so I'll see if they can be tested.
